spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/database
        username: stefan
        password: secret
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: create-drop
    web:
        error:
            include-message: always

server:
    port: 8080